name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint the content
        run: |
          yarn config set workspaces-experimental true
          yarn install
          yarn bootstrap
          yarn build
          yarn lint
          yarn test

  cdn:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 3

    needs:
      - test

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        run: |
          yarn config set workspaces-experimental true
          yarn setup

      - name: Push compiled content
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: cdn
          FOLDER: packages/embed-cdn/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
